config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :deputies, only: [:show, :index]

  devise_for :users
  root to: 'pages#home'

end

app/views/shared/deputy_modal/_deputy_contact.html.erb
<div class="tartan-card cover-position tartan-card-column-direction">

  <!-- rectangle left (hdouble) -->
  <%= link_to "https://www.google.fr/maps/place/#{@address.value} #{@address.city}", target: '_blank', class: "tartan-element tartan-element-hdouble bg-red" do %>
    <p>
      <%= @address.value %>
    </p>
    <p>
      <%= @address.postcode %>
    </p>
    <p>
      <%= @address.city %>
    </p>
  <% end %>
  <!-- rectangle left (hdouble) -->

  <!-- square top right -->
  <% if find_emails(@deputy).empty? %>
    <div class="tartan-element">
      <h3>
        <i class="fa fa-at"></i>
      </h3>
    </div>
  <% else %>
    <%= mail_to find_emails(@deputy).first, class: 'tartan-element bg-light-blue' do %>
      <h3>
        <i class="fa fa-at"></i>
      </h3>
    <% end %>
  <% end %>
  <!-- square top right -->

  <!-- square bottom right -->
  <% if find_emails(@deputy).count <= 1 %>
    <div class="tartan-element">
      <h3>
        <i class="fa fa-at"></i>
      </h3>
    </div>
  <% else %>
    <%= mail_to find_emails(@deputy)[1], class: 'tartan-element bg-gray' do %>
      <h3>
        <i class="fa fa-at"></i>
      </h3>
    <% end %>
  <% end %>
  <!-- square bottom right -->

</div>

app/views/shared/deputy_modal/_deputy_ext_info.html.erb
<div class="tartan-card cover-position tartan-card-column-direction">

  <!-- square top left -->
  <%= link_to @deputy.mandates.last.hatvp_page, class: 'tartan-element bg-red', target: '_blank' do %>
    <h3>
      <i class="fa fa-file-text-o"></i>
    </h3>
  <% end %>
  <!-- square top left -->

  <!-- square bottom left -->
  <% if @deputy.screen_name.length == 0 %>
    <div class="tartan-element">
      <h3>
        <i class="fa fa-twitter"></i>
      </h3>
    </div>
  <% else %>
    <%= link_to "https://twitter.com/#{@deputy.screen_name}", target: '_blank', class: 'tartan-element bg-light-blue' do %>
      <h3>
        <i class="fa fa-twitter"></i>
      </h3>
    <% end %>
  <% end %>
  <!-- square bottom left -->

  <!-- rectangle right (hdouble) -->
  <%= link_to "http://www2.assemblee-nationale.fr/deputes/fiche/OMC_#{@deputy.original_tag}", target: '_blank', class: "tartan-element tartan-element-hdouble bg-dark-blue" do %>
    <h3>
      <i class="fa fa-university"></i>
    </h3>
  <% end %>
  <!-- rectangle right (hdouble) -->

</div>

app/views/shared/deputy_modal/_deputy_id.html.erb
<div class="tartan-card cover-position">

  <!-- square top left -->
  <%= link_to deputies_path(search: { ini: @deputy.lastname[0] }), class: 'tartan-element bg-dark-blue' do %>
    <h3>
      <%= @deputy.lastname[0].capitalize %>
    </h3>
  <% end %>
  <!-- square top left -->

  <!-- square top right -->
  <%= link_to '', deputy_path(@deputy, search: params[:search]), class: 'tartan-element tartan-picture', style: "background-image: url(#{@deputy.picture})" %>
  <!-- square top right -->

  <!-- rectangle bottom (wdouble) -->
  <%= link_to deputies_path(search: { grp: @deputy.group.sigle }), class: 'tartan-element tartan-element-wdouble bg-red' do %>
    <h3>
      <%= @deputy.group.sigle %>
    </h3>
  <% end %>
  <!-- rectangle bottom (wdouble) -->

</div>

app/views/shared/deputy_modal/_deputy_mandate.html.erb
<div class="tartan-card cover-position">

  <!-- square top left -->
  <%= link_to "http://www2.assemblee-nationale.fr/deputes/fiche/OMC_#{@deputy.original_tag}", target: '_blank', class: 'tartan-element bg-red' do %>
    <p>
      Siège
    </p>
    <h3>
      #<%= @mandate.seat_num %>
    </h3>
  <% end %>
  <!-- square top left -->

  <% if params[:action] == 'index' %>
<!-- MODAL -->

    <!-- square top right -->
    <div class="tartan-element tartan-modal-nav bg-gray" data-dismiss="modal" data-toggle="modal" data-target="#deputy_modal_<%= @next_id.id %>" data-deputy=<%= @next_id.id %>>
      <h3>
        <i class="fa fa-arrow-right"></i>
      </h3>
    </div>
    <!-- square top right -->

<!-- MODAL -->
  <% else %>
<!-- NORMAL VERSION (show) -->

    <!-- square top right -->
    <%= link_to deputy_path(@next_id, search: params[:search]), class: 'tartan-element bg-gray' do %>
      <h3>
        <i class="fa fa-arrow-right"></i>
      </h3>
    <% end %>
    <!-- square top right -->


<!-- NORMAL VERSION (show) -->
  <% end %>

  <!-- rectangle bottom (wdouble) -->
  <%= link_to deputies_path(search: { dep: @circo.department_num }), class: 'tartan-element tartan-element-wdouble bg-dark-blue' do %>
    <p><strong>
      <%= "#{@circo.department} (#{@circo.department_num})" %>
    </strong></p>
    <p>
      <%= "#{ordinalize_FR(@circo.circo_num, 'F')} circonscription" %>
    </p>
  <% end %>
  <!-- rectangle bottom (wdouble) -->

</div>

app/views/shared/deputy_modal/_deputy_nav.html.erb
<div class="tartan-card cover-position">

  <!-- rectangle top (wdouble) -->
  <%= link_to deputy_path(@deputy, search: params[:search]), class: 'tartan-element tartan-element-wdouble bg-blue' do %>
    <p>
      <%= "#{@deputy.civ} #{@deputy.firstname} #{@deputy.lastname}" %>
    </p>
  <% end %>
  <!-- rectangle top (wdouble) -->

  <% if params[:action] == 'index' %>
<!-- MODAL -->

    <!-- square bottom left -->
    <div class="tartan-element tartan-modal-nav bg-gray"data-dismiss="modal" data-toggle="modal" data-target="#deputy_modal_<%= @previous_id.id %>" data-deputy=<%= @previous_id.id %>>
      <h3>
        <i class="fa fa-arrow-left"></i>
      </h3>
    </div>
    <!-- square bottom left -->

<!-- MODAL -->
  <% else %>
<!-- NORMAL VERSION (show) -->

    <!-- square bottom left -->
    <%= link_to deputy_path(@previous_id, search: params[:search]), class: 'tartan-element bg-gray' do %>
      <h3>
        <i class="fa fa-arrow-left"></i>
      </h3>
    <% end %>
    <!-- square bottom left -->

<!-- NORMAL VERSION (show) -->
  <% end %>

  <!-- square bottom right -->
  <%= link_to root_path, class: 'tartan-element bg-dark-blue' do %>
    <h3>
      <i class="fa fa-home"></i>
    </h3>
  <% end %>
  <!-- square bottom right -->
</div>

app/views/shared/deputy_modal/_deputy_pers_info.html.erb
<div class="tartan-card cover-position">

  <!-- rectangle top (wdouble) -->
  <%= link_to deputies_path(search: { pro: @deputy.job.category }), class: 'tartan-element tartan-element-wdouble bg-blue' do %>
    <p>
      <%= @deputy.job.label %>
    </p>
  <% end %>
  <!-- rectangle top (wdouble) -->

  <!-- square bottom left -->
  <%= link_to deputies_path(search: { age: find_age(@deputy)} ), class: 'tartan-element bg-dark-blue' do %>
    <h3>
      <%= find_age(@deputy) %>
    </h3>
    <p>
      ans
    </p>
  <% end %>
  <!-- square bottom left -->

  <!-- square bottom right -->
  <% if find_website(@deputy).length == 0 %>
    <div class="tartan-element">
      <h3>
        <i class="fa fa-external-link"></i>
      </h3>
    </div>
  <% else %>
    <%= link_to "http://#{find_website(@deputy)}", target: '_blank', class: 'tartan-element bg-gray' do %>
      <h3>
        <i class="fa fa-external-link"></i>
      </h3>
    <% end %>
  <% end %>
  <!-- square bottom right -->

</div>